from chargingstationmergedtool.parser.DataGouvParser import DataGouvParser
from chargingstationmergedtool.parser.OsmParser import OsmParser
from chargingstationmergedtool.parser.CsvParser import CsvParser